source = ~/.config/hypr/env.conf
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/general.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/rules.conf
source = ~/.config/hypr/config/workspaces.conf


##############################
# MONITOR & DISPLAY SETTINGS #
##############################

monitor = DP-3, 1920x1080@165, 0x0, 1
exec-once = swaybg -i $WALLPAPER


####################
# STARTUP PROGRAMS #
####################
 
exec-once = quickshell
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha"
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = swaybg -i $(cat ~/.config/wallpaper 2>/dev/null || echo $HOME/.config/hypr/wallpapers/default.jpg) -m fill
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard both
