###########
# IMPORTS #
###########

source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/cursor.conf
source = ~/.config/hypr/config/general.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/rules.conf


####################
# STARTUP PROGRAMS #
####################

exec-once = dunst
exec-once = eww daemon
exec-once = eww open bar
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard both
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha"


##############################
# MONITOR & DISPLAY SETTINGS #
##############################

monitor = DP-3, 1920x1080@165, 0x0, 1

# Wallpaper
exec-once = awww-daemon
exec-once = awww img ~/.config/hypr/wallpaper/Reze.png --transition-type fade

##########################
# ENVIRONEMENT VARIABLES #
##########################

# GTK Theme
env = GTK_THEME,Catppuccin-Mauve-Dark

# NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
env = __GL_GSYNC_ALLOWED,1

# Electron Apps Fix
env = ELECTRON_OZONE_PLATFORM_HINT,auto


##############
# WORKSPACES #
##############

# Default workspaces
workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true

# Special workspaces
workspace = special:discord, persistent:true
workspace = special:obs, persistent:true
workspace = special:satty, persistent:true
workspace = special:spotify, persistent:true
