$crust = rgb(11111b)
$mantle = rgb(181825)
$base = rgb(1e1e2e)
$surface0 = rgb(313244)
$surface1 = rgb(45475a)
$surface2 = rgb(585b70)
$overlay0 = rgb(6c7086)
$overlay1 = rgb(7f849c)
$overlay2 = rgb(9399b2)
$subtext0 = rgb(a6adc8)
$subtext1 = rgb(bac2de)
$text = rgb(cdd6f4)
$lavender = rgb(b4befe)
$blue = rgb(89b4fa)
$sapphire = rgb(74c7ec)
$sky = rgb(89dceb)
$teal = rgb(94e2d5)
$green = rgb(a6e3a1)
$yellow = rgb(f9e2af)
$peach = rgb(fab387)
$maroon = rgb(eba0ac)
$red = rgb(f38ba8)
$mauve = rgb(cba6f7)
$pink = rgb(f5c2e7)
$flamingo = rgb(f2cdcd)
$rosewater = rgb(f5e0dc)
$hl_shadow            = rgba(11111baa)
$hl_background        = rgb(1e1e2e)
