animations {
    enabled = true
    
    bezier = easeIn, 0.5, 0, 0.75, 0
    bezier = easeOut, 0.25, 1, 0.5, 1
    bezier = easeInOut, 0.75, 0, 0.25, 1
    bezier = linear, 0, 0, 1, 1
    bezier = linearSmooth, 0.5, 0.5, 0.75, 1
    bezier = quick, 0.15, 0, 0.1, 1

    animation = global, 1, 10, default
    animation = border, 1, 5, easeOut
    animation = windows, 1, 5, easeOut
    animation = windowsIn, 1, 2.5, easeOut, popin
    animation = windowsOut, 1, 1.8, easeIn, popin
    animation = windowsMove, 1, 6, easeOut, slide
    animation = zoomFactor, 1, 7, quick
    animation = fadeIn, 1, 1.5, linearSmooth
    animation = fadeOut, 1, 1.5, linearSmooth
    animation = fade, 1, 3, quick
    animation = layers, 1, 3, easeOut
    animation = layersIn, 1, 4, easeOut, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.8, linearSmooth
    animation = fadeLayersOut, 1, 1.4, linearSmooth
    animation = workspaces, 1, 5, easeInOut, slidevertfade
    animation = workspacesIn, 1, 5, easeInOut, slidefade
    animation = workspacesOut, 1, 5, easeInOut, slidefade
}
