env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = XCURSOR_SIZE,22
env = HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors
env = HYPRCURSOR_SIZE,22

cursor {
    no_break_fs_vrr = false
    hotspot_padding = 1
    enable_hyprcursor = 1
    hide_on_touch = 0
    no_hardware_cursors = 2
    inactive_timeout = 0
}
