env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = XCURSOR_SIZE,22
env = HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors
env = HYPRCURSOR_SIZE,22

cursor {
    enable_hyprcursor = 0
    no_hardware_cursors = 0
}
