############
# KEYBOARD #
############

input {
    kb_layout = fr
    kb_options = caps:shiftlock
    numlock_by_default = false
    repeat_rate = 25
    repeat_delay = 300
}

#########
# MOUSE #
#########

input {
    sensitivity = 0
    follow_mouse = 1
    force_no_accel = 1
}

##########
# CURSOR #
##########

env = XCURSOR_THEME,Windows-10
env = XCURSOR_SIZE,22
env = HYPRCURSOR_THEME,Windows-10
env = HYPRCURSOR_SIZE,22

cursor {
    enable_hyprcursor = 0
    no_hardware_cursors = 0
}
