source = ~/.config/hypr/env.conf

# Shortcuts
bindd = SUPER,       Q,       Open Kitty,             exec, $TERMINAL $SHELL
bindd = SUPER,       T,       Open VSCode,            exec, $EDITOR
bindd = SUPER,       E,       Open File Explorer,     exec, $EXPLORER
bindd = SUPER,       B,       Open Browser,           exec, $BROWSER
bindd = SUPER,       Super_L, Open Rofi Drun,         exec, $DRUN
bindd = SUPER,       W,       Open Rofi Wallpapers,   exec, ~/.config/hypr/scripts/wallpaper.sh
bindd = SUPER,       D,       Open Discord,           exec, $SPECIAL_WS discord discord $DISCORD
bindd = SUPER,       O,       Open OBS,               exec, $SPECIAL_WS obs com.obsproject.Studio obs
bindd = SUPER,       S,       Open Spotify,           exec, $SPECIAL_WS spotify Spotify spotify
bindd = SUPER,       G,       Open Steam,             exec, $SPECIAL_WS steam steam steam
bindd = SUPER,       V,       Toggle floating window, exec, hyprctl dispatch togglefloating && hyprctl dispatch resizeactive exact 1400 800
bindd = SUPER,       F,       Toggle fullscreen,      fullscreen
bindd = SUPER,       C,       Kill active window,     killactive,
bindd = SUPER SHIFT, C,       Color picker,           exec, hyprpicker -a --format=hex --notify --render-inactive
bindd = SUPER SHIFT, V,       Clipboard history,      exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bindd = SUPER SHIFT, R,       Reload Hyprland,        exec, hyprctl reload

# Screenshots
bind = , Print,        exec, FILE=/mnt/HDD/Pictures/Screenshots/$(date +%Y%m%d-%H%M%S).png && grim "$FILE" && satty --filename "$FILE"
bind = SUPER SHIFT, S, exec, FILE=/mnt/HDD/Pictures/Screenshots/$(date +%Y%m%d-%H%M%S).png && grim -g "$(slurp)" "$FILE" && satty --filename "$FILE"

# Window Management
bindm = SUPER, $LMB,       movewindow
bindm = SUPER, $RMB,       resizewindow
bind  = SUPER, left,       movefocus, l
bind  = SUPER, right,      movefocus, r
bind  = SUPER, up,         movefocus, u
bind  = SUPER, down,       movefocus, d
bind  = SUPER, mouse_down, exec, $SCROLL_WS up
bind  = SUPER, mouse_up,   exec, $SCROLL_WS down

# Workspace switching
bind = SUPER,       ampersand, workspace, 1
bind = SUPER,       eacute, workspace, 2
bind = SUPER,       quotedbl, workspace, 3
bind = SUPER,       apostrophe, workspace, 4
bind = SUPER,       parenleft, workspace, 5
bind = SUPER,       minus, workspace, 6
bind = SUPER,       egrave, workspace, 7
bind = SUPER,       underscore, workspace, 8
bind = SUPER,       ccedilla, workspace, 9
bind = SUPER,       agrave, workspace, 10

# Move to workspace
bind = SUPER SHIFT, ampersand, movetoworkspace, 1
bind = SUPER SHIFT, eacute, movetoworkspace, 2
bind = SUPER SHIFT, quotedbl, movetoworkspace, 3
bind = SUPER SHIFT, apostrophe, movetoworkspace, 4
bind = SUPER SHIFT, parenleft, movetoworkspace, 5
bind = SUPER SHIFT, minus, movetoworkspace, 6
bind = SUPER SHIFT, egrave, movetoworkspace, 7
bind = SUPER SHIFT, underscore, movetoworkspace, 8
bind = SUPER SHIFT, ccedilla, movetoworkspace, 9
bind = SUPER SHIFT, agrave, movetoworkspace, 10

# Media
bindel = , XF86AudioRaiseVolume,  exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+
bindel = , XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
bindel = , XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp,   exec, brightnessctl -e4 -n2 set 2%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 2%-
bindl  = , XF86AudioNext,         exec, playerctl next
bindl  = , XF86AudioPause,        exec, playerctl play-pause
bindl  = , XF86AudioPlay,         exec, playerctl play-pause
bindl  = , XF86AudioPrev,         exec, playerctl previous

input {
    kb_layout = fr
    kb_options = caps:shiftlock
    numlock_by_default = false
    follow_mouse = 1
    force_no_accel = 1
    repeat_rate = 25
    repeat_delay = 300
}