layerrule {
    name = blur-shells
    match:namespace = (quickshell|rofi)
    blur = true
    ignore_alpha = 0.5
}

windowrule {
    name = obs-workspace
    match:class = obs
    workspace = special:obs
}

windowrule {
    name = spotify-workspace
    match:class = spotify
    workspace = special:spotify
}

windowrule {
    name = steam-workspace
    match:class = steam
    match:title = negative:notificationtoasts.*
    match:title = negative:^$
    workspace = special:steam
}

windowrule {
    name = fix-steam-notifications
    match:class = steam
    match:title = notificationtoasts.*
    float = yes
    no_focus = yes
}

windowrule {
    name = fix-steam-popup-menus
    match:class = steam
    match:title = ^$
    float = yes
    pin = yes
}

windowrule {
    name = discord-workspace
    match:class = discord
    workspace = special:discord
}

windowrule {
    name = float-pavucontrol
    match:class = org.pulseaudio.pavucontrol
    float = yes
    size = 800 500
    center = yes
}

windowrule {
    name = float-centered-tools
    match:class = (com.gabm.satty|nwg-look)
    float = yes
    center = yes
    max_size = 1600 900
}

windowrule {
    name = float-steam-dialogs
    match:class = steam
    match:title = .+
    match:title = negative:(Steam|notificationtoasts.*)
    float = yes
}

windowrule {
    name = float-discord-dialogs
    match:class = discord
    match:title = negative:Discord
    float = yes
}

windowrule {
    name = float-nautilus-dialogs
    match:class = org.gnome.Nautilus
    match:title = (org.gnome.Nautilus|Select.*|Save.*|Open.*|Pick.*|File.*|Upload.*|Import.*|Choose.*)
    float = yes
}

windowrule {
    name = float-firefox-dialogs
    match:class = firefox
    match:title = (Library)
    float = yes
}

windowrule {
    name = float-modrinth-dialogs
    match:class = modrinth-app
    match:title = (Sign.*)
    float = yes
    size = 800 500
}
