layerrule {
    name = blur-quickshell
    match:namespace = quickshell
    blur = true
    ignore_alpha = 0.5
}

layerrule {
    name = blur-rofi
    match:namespace = rofi
    blur = true
    ignore_alpha = 0.5
}

windowrule {
    name = obs-workspace
    match:class = obs
    workspace = special:obs
}

windowrule {
    name = spotify-workspace
    match:class = spotify
    workspace = special:spotify
}

windowrule {
    name = steam-workspace
    match:class = steam
    workspace = special:steam
}

windowrule {
    name = discord-workspace
    match:class = discord
    workspace = special:discord
}

windowrule {
    name = float-pavucontrol
    match:class = org.pulseaudio.pavucontrol
    float = yes
    size = 800 500
    center = yes
}

windowrule {
    name = float-satty
    match:class = com.gabm.satty
    float = yes
    center = yes
    max_size = 1600 900
}

windowrule {
    name = float-nwg-look
    match:class = nwg-look
    float = yes
    center = yes
    max_size = 1600 900
}

windowrule {
    name = float-steam-dialogs
    match:class = ^(steam)$
    match:title = negative:Steam
    float = yes
    center = yes
}

windowrule {
    name = float-discord-dialogs
    match:class = ^(discord)$
    match:title = negative:Discord
    float = yes
    center = yes
}

windowrule {
    name = float-prism-launcher-dialogs
    match:class = (org.prismlauncher.PrismLauncher|xdg-desktop-portal-gtk)
    match:title = (Console window.*|Choose modpack)
    float = yes
    size = 1600 900
    center = yes
}
