##############
# WORKSPACES #
##############

# Default workspaces
workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true

# Special workspaces
workspace = special:discord, persistent:true
workspace = special:obs, persistent:true
workspace = special:spotify, persistent:true
workspace = special:steam, persistent:true
